# Machine Learning

## Application of machine learning

Here is a dataset with 237 samples including age, sex, height, and weight of children aged 11.5 to 20 years.

Age is given in months, not years, ranging from 139 to 250 months (i.e., 11.5 to 20 years).
The sex variable is binary: 0 for boys and 1 for girls.
Height in cm ranges from 128.27 cm to 182.88 cm.
The target variable, weight in kg, ranges from 22.9 kg to 77.78 kg.
Below is a short example of how to train a predictive model on this data.

In [27]:
import pandas as pd
import numpy as np

In [28]:
# Load dataset in panda's dataframe
df = pd.read_csv('https://raw.githubusercontent.com/OpenClassrooms-Student-Center/8063076-Initiez-vous-au-Machine-Learning/master/data/age_vs_poids_vs_taille_vs_sexe.csv')

In [29]:
# 5 first lines of the dataframe
df.head()

   sexe  age  taille  poids
0     1  147  151.13  45.80
1     0  160  150.62  35.60
2     1  148  149.86  43.08
3     0  149  144.78  41.72
4     0  156  156.21  49.21

In [30]:
# Statistics of the dataframe
df.describe()

             sexe         age      taille       poids
count  237.000000  237.000000  237.000000  237.000000
mean     0.468354  164.430380  155.865148   45.944430
std      0.500054   18.425767   10.021301    8.816557
min      0.000000  139.000000  128.270000   22.900000
25%      0.000000  148.000000  149.350000   38.550000
50%      0.000000  163.000000  156.210000   45.800000
75%      1.000000  178.000000  163.320000   50.790000
max      1.000000  250.000000  182.880000   77.780000

In [31]:
# predictive variables (also called features)
X = df[['sexe', 'age']]

# The target variable, weight
y = df.poids

In [32]:
# Import and instantiate the model

from sklearn.linear_model import LinearRegression
reg = LinearRegression()

In [33]:
# We train this model on the data using the fit method
reg.fit(X, y)

LinearRegression()

In [34]:
# and we get the score
print(f"R^2 : {np.round(reg.score(X, y), 3)}")

R^2 : 0.416

In [35]:
# and the a,b,c, coefficient of the linear regression
print(f" weight = {np.round(reg.coef_[0],  2)} * sex + {np.round(reg.coef_[1],  2)} * age  + noise")

 weight = -2.06 * sex + 0.3 * age  + noise

In [36]:
# features
X = df[['sexe', 'age', 'taille']]

# target
y = df.poids

# training of a new linear regression model
reg2 = LinearRegression()
reg2.fit(X,y)

# le score
print(f"R^2 : {np.round(reg2.score(X, y), 3)}")
# et les coefficients
print(f"weight = {np.round(reg.coef_[0],  2)} * sex + {np.round(reg.coef_[1],  2)} * age +  {np.round(reg2.coef_[2],  2)} * height + noise")

R^2 : 0.631
weight = -2.06 * sex + 0.3 * age +  0.55 * height + noise

In [37]:
# Weight prediction for a boy aged 150 months
reg.predict(np.array([[0, 150]]))

c:\Users\noxra\scoop\apps\python312\current\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([42.52765679])

In [38]:
# Weight prediction for a boy aged 150 months and 170 cm tall.
reg2.predict(np.array([[0, 150, 170]]))

c:\Users\noxra\scoop\apps\python312\current\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([52.14955185])

In [ ]:
# Predictions on all the samples in the dataset.

y_pred = reg.predict(df[['sexe', 'age']])
y_pred2 = reg2.predict(df[['sexe', 'age', 'taille']])

from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error
print("1st Model: weight ~ sex + age")
print(f"\tmean_squared_error(y, y_pred): {mean_squared_error(y, y_pred)}")
print(f"\tmean_absolute_error(y, y_pred): {mean_absolute_error(y, y_pred)}")
print(f"\tmean_absolute_percentage_error(y, y_pred): {mean_absolute_percentage_error(y, y_pred)}")
print()



print("2nd Model: weight ~ sex + age + height")
print(f"\tmean_squared_error(y, y_pred): {mean_squared_error(y, y_pred2)}")
print(f"\tmean_absolute_error(y, y_pred): {mean_absolute_error(y, y_pred2)}")
print(f"\tmean_absolute_percentage_error(y, y_pred): {mean_absolute_percentage_error(y, y_pred2)}")

1st Model: weight ~ sex + age
	mean_squared_error(y, y_pred): 45.17470814507523
	mean_absolute_error(y, y_pred): 5.219181502513357
	mean_absolute_percentage_error(y, y_pred): 0.11643376955710255

2nd Model: weight ~ sex + age + height
	mean_squared_error(y, y_pred): 28.59911226330148
	mean_absolute_error(y, y_pred): 4.1635921045133335
	mean_absolute_percentage_error(y, y_pred): 0.09053096861870082

## Models

## Predictive models

## Linear Regression

In [ ]:
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [ ]:
dataset_url = "https://raw.githubusercontent.com/OpenClassrooms-Student-Center/8063076-Initiez-vous-au-Machine-Learning/master/data/advertising.csv"

df = pd.read_csv(dataset_url)

In [ ]:
df.head()

In [ ]:
df.describe()

In [ ]:
df.info()

In [ ]:
fig, ax = plt.subplots(1,3, figsize = (15,5))

plt.subplot(1,3,1)
sns.regplot(x = df[['tv']],y  =  df.ventes)
plt.ylabel('ventes')
plt.xlabel('TV')
plt.title('ventes = a * tv  + b')
plt.grid()
sns.despine()

plt.subplot(1,3,2)
sns.regplot(x = df[['radio']],y  =  df.ventes)
plt.ylabel('ventes')
plt.xlabel('radio')
plt.title('ventes = a * radio + b')
plt.grid()
sns.despine()

plt.subplot(1,3,3)
res = sns.regplot(x = df[['journaux']],y  =  df.ventes)
plt.ylabel('ventes')
plt.xlabel('journaux')
plt.title('ventes = a * journaux + b')
plt.grid()
sns.despine()

plt.tight_layout()
plt.show()

In [ ]:
df.corr()

In [ ]:
reg = LinearRegression()

In [ ]:
X = df[['tv','radio','journaux']]
y = df.ventes

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [ ]:
# Entrainons le modele
reg.fit(X_train, y_train)

In [ ]:
y_pred_test = reg.predict(X_test)

In [ ]:
print(f"RMSE: {mean_squared_error(y_test, y_pred_test)}")
print(f"RMSE: {mean_absolute_percentage_error(y_test, y_pred_test)}")

In [ ]:
# Creer la variable quadratique tv^2
df['tv2'] = df.tv**2

variables = ['tv','radio','journaux','tv2']

In [ ]:
# Instancier le Scaler
scaler = MinMaxScaler()

# et l'appliquer 
data_array = scaler.fit_transform(df[variables])

# transformer le array en dataframe (c'est plus friendly)
df_scaled = pd.DataFrame(data_array,  columns = variables)

# verifier que les min et max des variables sont tous 0 et 1
df_scaled.describe().loc[['min','max']]

In [ ]:
# scindons les donnees en test et train
X = df_scaled[variables]
y = df.ventes

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [ ]:
# entrainons le modele
reg = LinearRegression()
reg.fit(X_train, y_train)

In [ ]:
# Prediction sur le test set
y_pred_test = reg.predict(X_test)

# Scores
print(f"-- Regression ventes ~ radio + journaux + tv + tv^2")
print(f"\tRMSE: {mean_squared_error(y_test, y_pred_test)}")
print(f"\tMAPE: {mean_absolute_percentage_error(y_test, y_pred_test)}")

In [ ]:
# créons la variable tv * radio

df['tv_radio'] = df.tv * df.radio

In [ ]:
regressions = {
    'simple: y ~ tv + radio + journaux'  :     ['tv','radio','journaux'],
    'quadratique: y ~ tv + radio + journaux + tv2': ['tv','radio','journaux', 'tv2'],
    'terme croisée: y ~ tv + radio + journaux + tv*radio':['tv','radio','journaux', 'tv_radio']
}

In [ ]:
# la varibale cible est toujours la même
y = df.ventes


# boucle sur les régressions
for title, variables in regressions.items():
    # il faut limiter l'amplitude sur toutes les variables predictrices
    scaler = MinMaxScaler()
    data_array = scaler.fit_transform(df[variables])
    # df_scaled = pd.DataFrame(data_array, columns = variables)
    
    # X = df_scaled[variables]
    # Train test split
    X_train, X_test, y_train, y_test = train_test_split(data_array, y, test_size=0.20, random_state=42)

    # entrainer le modele
    reg.fit(X_train, y_train)
    # Prediction sur le test set
    y_pred_test = reg.predict(X_test)

    # Scores
    print(f"\n-- Regression {title}")
    print(f"\tRMSE: {mean_squared_error(y_test, y_pred_test)}")
    print(f"\tMAPE: {mean_absolute_percentage_error(y_test, y_pred_test)}")

## Clustering with K-means

## Dataset

## Model performance